### ISSUE TITLE
Practica Visualización

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo-kem#1]
[Practica Visualización.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-equipo-kem/files/15486212/Practica.Visualizacion.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 19
